# Generated by Django 3.2.2 on 2021-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('poster', models.CharField(max_length=300)),
                ('imdbID', models.CharField(max_length=300)),
                ('api', models.CharField(max_length=300)),
                ('languages', models.CharField(default='', max_length=300)),
                ('actors', models.CharField(default='', max_length=300)),
                ('directors', models.CharField(default='', max_length=300)),
                ('size', models.IntegerField(default='')),
                ('publish', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='View',
        ),
    ]
