# Generated by Django 3.2.2 on 2021-05-09 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210509_2131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='size',
            field=models.IntegerField(default=0),
        ),
    ]
