# Generated by Django 3.2.2 on 2021-05-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20210509_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='size',
            field=models.CharField(default='', max_length=300),
        ),
    ]
