# Generated by Django 3.2.2 on 2021-05-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_movie_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screenshot1',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot2',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot3',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='screenshot4',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
