# Generated by Django 3.2.2 on 2021-05-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_auto_20210510_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='mega',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
