# Generated by Django 3.2.2 on 2021-05-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_movie_mega'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='google',
            field=models.CharField(default='#', max_length=300),
        ),
    ]
