# Generated by Django 3.2.2 on 2021-05-11 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0014_movie_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('B', 'Bollywood'), ('H', 'Hollywood'), ('A', 'Animated'), ('S', 'South')], max_length=1),
        ),
    ]
